### ISSUE TITLE
Error building VuePress with yarn 

### ISSUE THREAD

**Issue by sarimabbas** [adrienhobbs/vue-lazyload-video#3]
Thank you for your work on this package. Unfortunately, I'm getting the following error when building VuePress website. Strangely, everything works in dev mode. Would you be able to assist? Thank you!

```
ReferenceError: window is not defined
    at Module.fb15 (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:2504:1)
    at __webpack_require__ (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:474:0)
    at server-bundle.js:781:18
    at Object.5020 (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:541:0)
    at __webpack_require__ (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:21:0)
    at Module.fb15 (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:4144:0)
    at __webpack_require__ (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:21:0)
    at server-bundle.js:328:18
    at Object.<anonymous> (node_modules/vue-lazyload-video/dist/vue-lazyload-video.common.js:88:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:8196:33)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:4759:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
    at Object.<anonymous> (server-bundle.js:121:10)
error Command failed with exit code 1.
```

**Comment by adrienhobbs** [comment]
Hi there @sarimabbas - unfortunately this package and its dependencies weren't created with server side rendering in mind - which I'm assuming is why you're getting some errors when trying to build the static site. Perhaps in the future I can look towards making this SSR compatible.

**Comment by sarimabbas** [comment]
I understand, thanks for your response : )

**Comment by adrienhobbs** [comment]
Of course. Have you done any Vue plugin development before? I haven’t done
much research on SSR and how to handle it in Vue plugins. I’d definitely
invite your help if so inclined! Do you know of any other plugins I could use as an example?

**Comment by sarimabbas** [comment]
I haven’t done any before, but I’m happy to learn! I can do some more research into this and let you know what I find

**Comment by adrienhobbs** [comment]
Sounds great. Let me know if any questions come up!
